# Create Security Group For RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable TCP on port 3306
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.200.0.0/16
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.200.3.0/24
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.200.4.0/24
      Tags:
        - Key: Name
          Value: RDS Security Group2   

# Create RDS MySqlDb in Private Subnet
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBSecurityGroups: 
        - Ref: RDSSecurityGroup
      Engine: MySQL
      EngineVersion: 8.0.23
      StorageType: gp2
      AvailabilityZone: ap-south-1b
      MasterUsername: admin
      MasterUserPassword: admin123
      Tags:
        - Key: Name
          Value: MySql RDS
      VPCSecurityGroups: 
        - Ref: PrivateSecurityGroup
  

# Create Private Subnet group for MySqldb RDS      
  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for mysqldb RDS
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Tags: 
        - Key: Name
          Value: RDS Subnet Group2

# Export RDS Security Group ID
  RDSSecurityGroup:
    Description: RDS Security Group ID
    Export:
      Name: !Sub ${AWS::StackName}-RDSSecurityGroup
    Value: !Ref RDSSecurityGroup