AWSTemplateFormatVersion: 2010-09-09

Description: This template will create RDS MySqldb in private subnet and create private subnet group for mysqldb and also create security group for RDS

Parameters:
  DBInstanceID:
    Default: mysqldbinstance
    Description: My database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: mysqldb
    Description: My Sql database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.  
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '1'
    MaxValue: '20'
    ConstraintDescription: must be between 20 and 65536 GiB.
    
Resources:
# Create RDS MySqlDb in Private Subnet
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: 8.0.23
      StorageType: gp2
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      MasterUsername: mysqldb
      MasterUserPassword: abcdefghi
      Tags:
        - Key: Name
          Value: MySql RDS

# Create Private Subnet group for MySqldb RDS      
  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        - !Ref PrivateSubnet
        - !Ref PublicSubnet
      Tags: 
        - Key: Name
          Value: RDS Subnet Group

# Create Security Group For RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable TCP on port 3306
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.200.0.0/16
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 10.200.1.0/24
      Tags:
        - Key: Name
          Value: RDS Security Group   
